// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwi1bfBuJGGBST5aO1_GhvZTbmNk1aTgY',
    appId: '1:441828524688:android:bff5d7e904875a21ae4e15',
    messagingSenderId: '441828524688',
    projectId: 'haruviet-809ef',
    storageBucket: 'haruviet-809ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCid6V5r7d27SD_ZCZCwowYzFyJ8J8G808',
    appId: '1:441828524688:ios:9e9b0a2d32138c2eae4e15',
    messagingSenderId: '441828524688',
    projectId: 'haruviet-809ef',
    storageBucket: 'haruviet-809ef.appspot.com',
    androidClientId:
        '441828524688-7uji4ar0islsihrv6uj8v88cp8l1huce.apps.googleusercontent.com',
    iosClientId:
        '441828524688-o4fufjgofptnpmqbribbvjf4g0qtense.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoApp',
  );
}
